"""add url owner

Revision ID: 1b2bd4dcedab
Revises: 6466dbfcd1d0
Create Date: 2025-02-14 22:09:35.951050

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from models import Url

# revision identifiers, used by Alembic.
revision: str = "1b2bd4dcedab"
down_revision: Union[str, None] = "6466dbfcd1d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # adding owner is breaking changes, we have to delete all existing url
    op.execute(sa.delete(Url))
    op.add_column("urls", sa.Column("owner", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("urls", "owner")
    # ### end Alembic commands ###
