"""add country to url redirect analytics

Revision ID: 3296ff8ccee1
Revises: 804f08da897f
Create Date: 2025-02-20 23:53:05.902195

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3296ff8ccee1"
down_revision: Union[str, None] = "804f08da897f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "url_redirect_usages",
        sa.Column("country", sa.String(), server_default="unknown", nullable=False),
    )
    op.drop_constraint(
        "url_redirect_usages_url_key_key", "url_redirect_usages", type_="unique"
    )
    op.create_unique_constraint(
        "url_redirect_usages_key_country_unique",
        "url_redirect_usages",
        ["url_key", "country"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "url_redirect_usages_key_country_unique", "url_redirect_usages", type_="unique"
    )
    op.create_unique_constraint(
        "url_redirect_usages_url_key_key", "url_redirect_usages", ["url_key"]
    )
    op.drop_column("url_redirect_usages", "country")
    # ### end Alembic commands ###
