"""add url redirect analytics

Revision ID: 804f08da897f
Revises: 1b2bd4dcedab
Create Date: 2025-02-20 23:14:44.563339

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "804f08da897f"
down_revision: Union[str, None] = "1b2bd4dcedab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_redirect_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url_key", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["url_key"],
            ["urls.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("url_redirect_usages")
    # ### end Alembic commands ###
