"""url_usage_on_delete_cascade

Revision ID: a22af0c84529
Revises: 4a27617b8837
Create Date: 2025-03-09 17:44:51.305707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a22af0c84529"
down_revision: Union[str, None] = "4a27617b8837"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "url_redirect_usages_url_key_fkey", "url_redirect_usages", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "url_redirect_usages", "urls", ["url_key"], ["key"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "url_redirect_usages", type_="foreignkey")
    op.create_foreign_key(
        "url_redirect_usages_url_key_fkey",
        "url_redirect_usages",
        "urls",
        ["url_key"],
        ["key"],
    )
    # ### end Alembic commands ###
