name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        poetry-version: ["1.8.4"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry install
      - name: Lint with black
        run: poetry run -- black --check **/*.py
      - name: Lint with flake8
        run: poetry run -- flake8
      - name: Lint with isort
        run: poetry run -- isort **/*.py --check
      - name: Run test
        run: poetry run -- pytest
